/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CreditRegistryV3 {
  export type CollateralDataStruct = {
    collateralToken: AddressLike;
    collateralValueUsd18: BigNumberish;
    principalUsd18: BigNumberish;
    userScoreAtBorrow: BigNumberish;
  };

  export type CollateralDataStructOutput = [
    collateralToken: string,
    collateralValueUsd18: bigint,
    principalUsd18: bigint,
    userScoreAtBorrow: bigint
  ] & {
    collateralToken: string;
    collateralValueUsd18: bigint;
    principalUsd18: bigint;
    userScoreAtBorrow: bigint;
  };

  export type CrossChainScoreStruct = {
    overallScore: BigNumberish;
    totalLoans: BigNumberish;
    repaidLoans: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type CrossChainScoreStructOutput = [
    overallScore: bigint,
    totalLoans: bigint,
    repaidLoans: bigint,
    updatedAt: bigint
  ] & {
    overallScore: bigint;
    totalLoans: bigint;
    repaidLoans: bigint;
    updatedAt: bigint;
  };

  export type GovernanceActivityStruct = {
    voteCount: BigNumberish;
    proposalCount: BigNumberish;
    lastVoteTimestamp: BigNumberish;
    lastProposalTimestamp: BigNumberish;
  };

  export type GovernanceActivityStructOutput = [
    voteCount: bigint,
    proposalCount: bigint,
    lastVoteTimestamp: bigint,
    lastProposalTimestamp: bigint
  ] & {
    voteCount: bigint;
    proposalCount: bigint;
    lastVoteTimestamp: bigint;
    lastProposalTimestamp: bigint;
  };

  export type KYCProofStruct = {
    credentialHash: BytesLike;
    verifiedAt: BigNumberish;
    expiresAt: BigNumberish;
  };

  export type KYCProofStructOutput = [
    credentialHash: string,
    verifiedAt: bigint,
    expiresAt: bigint
  ] & { credentialHash: string; verifiedAt: bigint; expiresAt: bigint };

  export type LoanRecordStruct = {
    loanId: BigNumberish;
    borrower: AddressLike;
    principalUsd18: BigNumberish;
    repaidUsd18: BigNumberish;
    timestamp: BigNumberish;
    status: BigNumberish;
    lender: AddressLike;
  };

  export type LoanRecordStructOutput = [
    loanId: bigint,
    borrower: string,
    principalUsd18: bigint,
    repaidUsd18: bigint,
    timestamp: bigint,
    status: bigint,
    lender: string
  ] & {
    loanId: bigint;
    borrower: string;
    principalUsd18: bigint;
    repaidUsd18: bigint;
    timestamp: bigint;
    status: bigint;
    lender: string;
  };

  export type StakeInfoStruct = {
    amount: BigNumberish;
    lockUntil: BigNumberish;
  };

  export type StakeInfoStructOutput = [amount: bigint, lockUntil: bigint] & {
    amount: bigint;
    lockUntil: bigint;
  };
}

export interface CreditRegistryV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCCIPSenders"
      | "authorizedGovernance"
      | "authorizedLenders"
      | "crossChainScores"
      | "getCollateralData"
      | "getCrossChainScore"
      | "getFirstSeen"
      | "getGovernanceActivity"
      | "getKYCProof"
      | "getLoan"
      | "getLoanIdsByBorrower"
      | "getStakeInfo"
      | "getUserCollateralAssets"
      | "governanceActivity"
      | "isKYCVerified"
      | "kycIssuer"
      | "kycProofs"
      | "loanCollateralData"
      | "owner"
      | "receiveCrossChainReputation"
      | "recordCollateralData"
      | "recordProposal"
      | "recordVote"
      | "registerLiquidation"
      | "registerLoan"
      | "registerRepayment"
      | "renounceOwnership"
      | "setAuthorizedCCIPSender"
      | "setAuthorizedGovernance"
      | "setAuthorizedLender"
      | "setKYCIssuer"
      | "stake"
      | "stakes"
      | "stakingToken"
      | "submitKYCProof"
      | "transferOwnership"
      | "unstake"
      | "walletFirstSeen"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CCIPSenderAuthorized"
      | "CollateralDataRecorded"
      | "CrossChainReputationReceived"
      | "FirstSeenRecorded"
      | "GovernanceAuthorized"
      | "KYCVerified"
      | "LenderAuthorized"
      | "LiquidationRegistered"
      | "LoanRegistered"
      | "OwnershipTransferred"
      | "ProposalRecorded"
      | "RepaymentRegistered"
      | "StakeDeposited"
      | "StakeWithdrawn"
      | "VoteRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCCIPSenders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedLenders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "crossChainScores",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollateralData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCrossChainScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFirstSeen",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGovernanceActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getKYCProof",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanIdsByBorrower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCollateralAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceActivity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKYCVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "kycIssuer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "kycProofs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loanCollateralData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveCrossChainReputation",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCollateralData",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordProposal",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLiquidation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLoan",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRepayment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCCIPSender",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedGovernance",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedLender",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "stakingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitKYCProof",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "walletFirstSeen",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCCIPSenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedLenders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "crossChainScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollateralData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCrossChainScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFirstSeen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGovernanceActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKYCProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanIdsByBorrower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCollateralAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceActivity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKYCVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kycIssuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kycProofs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanCollateralData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveCrossChainReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCollateralData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCCIPSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedLender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitKYCProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletFirstSeen",
    data: BytesLike
  ): Result;
}

export namespace CCIPSenderAuthorizedEvent {
  export type InputTuple = [sender: AddressLike, allowed: boolean];
  export type OutputTuple = [sender: string, allowed: boolean];
  export interface OutputObject {
    sender: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralDataRecordedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    collateralToken: AddressLike,
    collateralValueUsd18: BigNumberish,
    userScore: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    collateralToken: string,
    collateralValueUsd18: bigint,
    userScore: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    collateralToken: string;
    collateralValueUsd18: bigint;
    userScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainReputationReceivedEvent {
  export type InputTuple = [
    user: AddressLike,
    sourceChainSelector: BigNumberish,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    sourceChainSelector: bigint,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    sourceChainSelector: bigint;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirstSeenRecordedEvent {
  export type InputTuple = [wallet: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [wallet: string, timestamp: bigint];
  export interface OutputObject {
    wallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GovernanceAuthorizedEvent {
  export type InputTuple = [governance: AddressLike, allowed: boolean];
  export type OutputTuple = [governance: string, allowed: boolean];
  export interface OutputObject {
    governance: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifiedEvent {
  export type InputTuple = [
    user: AddressLike,
    credentialHash: BytesLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    credentialHash: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    credentialHash: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LenderAuthorizedEvent {
  export type InputTuple = [lender: AddressLike, allowed: boolean];
  export type OutputTuple = [lender: string, allowed: boolean];
  export interface OutputObject {
    lender: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationRegisteredEvent {
  export type InputTuple = [
    borrower: AddressLike,
    loanId: BigNumberish,
    amountUsd18: BigNumberish,
    timestamp: BigNumberish,
    liquidator: AddressLike
  ];
  export type OutputTuple = [
    borrower: string,
    loanId: bigint,
    amountUsd18: bigint,
    timestamp: bigint,
    liquidator: string
  ];
  export interface OutputObject {
    borrower: string;
    loanId: bigint;
    amountUsd18: bigint;
    timestamp: bigint;
    liquidator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRegisteredEvent {
  export type InputTuple = [
    borrower: AddressLike,
    loanId: BigNumberish,
    principalUsd18: BigNumberish,
    timestamp: BigNumberish,
    lender: AddressLike
  ];
  export type OutputTuple = [
    borrower: string,
    loanId: bigint,
    principalUsd18: bigint,
    timestamp: bigint,
    lender: string
  ];
  export interface OutputObject {
    borrower: string;
    loanId: bigint;
    principalUsd18: bigint;
    timestamp: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRecordedEvent {
  export type InputTuple = [
    proposer: AddressLike,
    proposalId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposer: string,
    proposalId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposer: string;
    proposalId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentRegisteredEvent {
  export type InputTuple = [
    borrower: AddressLike,
    loanId: BigNumberish,
    amountUsd18: BigNumberish,
    timestamp: BigNumberish,
    payer: AddressLike
  ];
  export type OutputTuple = [
    borrower: string,
    loanId: bigint,
    amountUsd18: bigint,
    timestamp: bigint,
    payer: string
  ];
  export interface OutputObject {
    borrower: string;
    loanId: bigint;
    amountUsd18: bigint;
    timestamp: bigint;
    payer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDepositedEvent {
  export type InputTuple = [
    staker: AddressLike,
    amount: BigNumberish,
    lockUntil: BigNumberish
  ];
  export type OutputTuple = [staker: string, amount: bigint, lockUntil: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
    lockUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [staker: AddressLike, amount: BigNumberish];
  export type OutputTuple = [staker: string, amount: bigint];
  export interface OutputObject {
    staker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRecordedEvent {
  export type InputTuple = [
    voter: AddressLike,
    proposalId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    proposalId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    voter: string;
    proposalId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreditRegistryV3 extends BaseContract {
  connect(runner?: ContractRunner | null): CreditRegistryV3;
  waitForDeployment(): Promise<this>;

  interface: CreditRegistryV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCCIPSenders: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  authorizedGovernance: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  authorizedLenders: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  crossChainScores: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        overallScore: bigint;
        totalLoans: bigint;
        repaidLoans: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getCollateralData: TypedContractMethod<
    [loanId: BigNumberish],
    [CreditRegistryV3.CollateralDataStructOutput],
    "view"
  >;

  getCrossChainScore: TypedContractMethod<
    [user: AddressLike, chainSelector: BigNumberish],
    [CreditRegistryV3.CrossChainScoreStructOutput],
    "view"
  >;

  getFirstSeen: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getGovernanceActivity: TypedContractMethod<
    [user: AddressLike],
    [CreditRegistryV3.GovernanceActivityStructOutput],
    "view"
  >;

  getKYCProof: TypedContractMethod<
    [user: AddressLike],
    [CreditRegistryV3.KYCProofStructOutput],
    "view"
  >;

  getLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [CreditRegistryV3.LoanRecordStructOutput],
    "view"
  >;

  getLoanIdsByBorrower: TypedContractMethod<
    [borrower: AddressLike],
    [bigint[]],
    "view"
  >;

  getStakeInfo: TypedContractMethod<
    [user: AddressLike],
    [CreditRegistryV3.StakeInfoStructOutput],
    "view"
  >;

  getUserCollateralAssets: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  governanceActivity: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        voteCount: bigint;
        proposalCount: bigint;
        lastVoteTimestamp: bigint;
        lastProposalTimestamp: bigint;
      }
    ],
    "view"
  >;

  isKYCVerified: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  kycIssuer: TypedContractMethod<[], [string], "view">;

  kycProofs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        credentialHash: string;
        verifiedAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  loanCollateralData: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        collateralToken: string;
        collateralValueUsd18: bigint;
        principalUsd18: bigint;
        userScoreAtBorrow: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  receiveCrossChainReputation: TypedContractMethod<
    [
      user: AddressLike,
      sourceChainSelector: BigNumberish,
      overallScore: BigNumberish,
      totalLoans: BigNumberish,
      repaidLoans: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordCollateralData: TypedContractMethod<
    [
      loanId: BigNumberish,
      collateralToken: AddressLike,
      collateralValueUsd18: BigNumberish,
      userScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordProposal: TypedContractMethod<
    [proposer: AddressLike, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordVote: TypedContractMethod<
    [voter: AddressLike, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerLiquidation: TypedContractMethod<
    [loanId: BigNumberish, recoveredUsd18: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerLoan: TypedContractMethod<
    [borrower: AddressLike, principalUsd18: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  registerRepayment: TypedContractMethod<
    [loanId: BigNumberish, amountUsd18: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedCCIPSender: TypedContractMethod<
    [sender: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setAuthorizedGovernance: TypedContractMethod<
    [governance: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setAuthorizedLender: TypedContractMethod<
    [lender: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setKYCIssuer: TypedContractMethod<
    [_kycIssuer: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  stakes: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; lockUntil: bigint }],
    "view"
  >;

  stakingToken: TypedContractMethod<[], [string], "view">;

  submitKYCProof: TypedContractMethod<
    [credentialHash: BytesLike, expiresAt: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  walletFirstSeen: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCCIPSenders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizedGovernance"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "authorizedLenders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "crossChainScores"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        overallScore: bigint;
        totalLoans: bigint;
        repaidLoans: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCollateralData"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [CreditRegistryV3.CollateralDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCrossChainScore"
  ): TypedContractMethod<
    [user: AddressLike, chainSelector: BigNumberish],
    [CreditRegistryV3.CrossChainScoreStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFirstSeen"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGovernanceActivity"
  ): TypedContractMethod<
    [user: AddressLike],
    [CreditRegistryV3.GovernanceActivityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKYCProof"
  ): TypedContractMethod<
    [user: AddressLike],
    [CreditRegistryV3.KYCProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [CreditRegistryV3.LoanRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoanIdsByBorrower"
  ): TypedContractMethod<[borrower: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getStakeInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [CreditRegistryV3.StakeInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCollateralAssets"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "governanceActivity"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        voteCount: bigint;
        proposalCount: bigint;
        lastVoteTimestamp: bigint;
        lastProposalTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isKYCVerified"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycIssuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "kycProofs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        credentialHash: string;
        verifiedAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanCollateralData"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        collateralToken: string;
        collateralValueUsd18: bigint;
        principalUsd18: bigint;
        userScoreAtBorrow: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveCrossChainReputation"
  ): TypedContractMethod<
    [
      user: AddressLike,
      sourceChainSelector: BigNumberish,
      overallScore: BigNumberish,
      totalLoans: BigNumberish,
      repaidLoans: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordCollateralData"
  ): TypedContractMethod<
    [
      loanId: BigNumberish,
      collateralToken: AddressLike,
      collateralValueUsd18: BigNumberish,
      userScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordProposal"
  ): TypedContractMethod<
    [proposer: AddressLike, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordVote"
  ): TypedContractMethod<
    [voter: AddressLike, proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerLiquidation"
  ): TypedContractMethod<
    [loanId: BigNumberish, recoveredUsd18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerLoan"
  ): TypedContractMethod<
    [borrower: AddressLike, principalUsd18: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRepayment"
  ): TypedContractMethod<
    [loanId: BigNumberish, amountUsd18: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedCCIPSender"
  ): TypedContractMethod<
    [sender: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedGovernance"
  ): TypedContractMethod<
    [governance: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedLender"
  ): TypedContractMethod<
    [lender: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setKYCIssuer"
  ): TypedContractMethod<[_kycIssuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; lockUntil: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakingToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitKYCProof"
  ): TypedContractMethod<
    [credentialHash: BytesLike, expiresAt: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "walletFirstSeen"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "CCIPSenderAuthorized"
  ): TypedContractEvent<
    CCIPSenderAuthorizedEvent.InputTuple,
    CCIPSenderAuthorizedEvent.OutputTuple,
    CCIPSenderAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralDataRecorded"
  ): TypedContractEvent<
    CollateralDataRecordedEvent.InputTuple,
    CollateralDataRecordedEvent.OutputTuple,
    CollateralDataRecordedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainReputationReceived"
  ): TypedContractEvent<
    CrossChainReputationReceivedEvent.InputTuple,
    CrossChainReputationReceivedEvent.OutputTuple,
    CrossChainReputationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FirstSeenRecorded"
  ): TypedContractEvent<
    FirstSeenRecordedEvent.InputTuple,
    FirstSeenRecordedEvent.OutputTuple,
    FirstSeenRecordedEvent.OutputObject
  >;
  getEvent(
    key: "GovernanceAuthorized"
  ): TypedContractEvent<
    GovernanceAuthorizedEvent.InputTuple,
    GovernanceAuthorizedEvent.OutputTuple,
    GovernanceAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerified"
  ): TypedContractEvent<
    KYCVerifiedEvent.InputTuple,
    KYCVerifiedEvent.OutputTuple,
    KYCVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "LenderAuthorized"
  ): TypedContractEvent<
    LenderAuthorizedEvent.InputTuple,
    LenderAuthorizedEvent.OutputTuple,
    LenderAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationRegistered"
  ): TypedContractEvent<
    LiquidationRegisteredEvent.InputTuple,
    LiquidationRegisteredEvent.OutputTuple,
    LiquidationRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "LoanRegistered"
  ): TypedContractEvent<
    LoanRegisteredEvent.InputTuple,
    LoanRegisteredEvent.OutputTuple,
    LoanRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRecorded"
  ): TypedContractEvent<
    ProposalRecordedEvent.InputTuple,
    ProposalRecordedEvent.OutputTuple,
    ProposalRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentRegistered"
  ): TypedContractEvent<
    RepaymentRegisteredEvent.InputTuple,
    RepaymentRegisteredEvent.OutputTuple,
    RepaymentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "StakeDeposited"
  ): TypedContractEvent<
    StakeDepositedEvent.InputTuple,
    StakeDepositedEvent.OutputTuple,
    StakeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "VoteRecorded"
  ): TypedContractEvent<
    VoteRecordedEvent.InputTuple,
    VoteRecordedEvent.OutputTuple,
    VoteRecordedEvent.OutputObject
  >;

  filters: {
    "CCIPSenderAuthorized(address,bool)": TypedContractEvent<
      CCIPSenderAuthorizedEvent.InputTuple,
      CCIPSenderAuthorizedEvent.OutputTuple,
      CCIPSenderAuthorizedEvent.OutputObject
    >;
    CCIPSenderAuthorized: TypedContractEvent<
      CCIPSenderAuthorizedEvent.InputTuple,
      CCIPSenderAuthorizedEvent.OutputTuple,
      CCIPSenderAuthorizedEvent.OutputObject
    >;

    "CollateralDataRecorded(uint256,address,uint256,uint16)": TypedContractEvent<
      CollateralDataRecordedEvent.InputTuple,
      CollateralDataRecordedEvent.OutputTuple,
      CollateralDataRecordedEvent.OutputObject
    >;
    CollateralDataRecorded: TypedContractEvent<
      CollateralDataRecordedEvent.InputTuple,
      CollateralDataRecordedEvent.OutputTuple,
      CollateralDataRecordedEvent.OutputObject
    >;

    "CrossChainReputationReceived(address,uint64,uint16,uint256)": TypedContractEvent<
      CrossChainReputationReceivedEvent.InputTuple,
      CrossChainReputationReceivedEvent.OutputTuple,
      CrossChainReputationReceivedEvent.OutputObject
    >;
    CrossChainReputationReceived: TypedContractEvent<
      CrossChainReputationReceivedEvent.InputTuple,
      CrossChainReputationReceivedEvent.OutputTuple,
      CrossChainReputationReceivedEvent.OutputObject
    >;

    "FirstSeenRecorded(address,uint256)": TypedContractEvent<
      FirstSeenRecordedEvent.InputTuple,
      FirstSeenRecordedEvent.OutputTuple,
      FirstSeenRecordedEvent.OutputObject
    >;
    FirstSeenRecorded: TypedContractEvent<
      FirstSeenRecordedEvent.InputTuple,
      FirstSeenRecordedEvent.OutputTuple,
      FirstSeenRecordedEvent.OutputObject
    >;

    "GovernanceAuthorized(address,bool)": TypedContractEvent<
      GovernanceAuthorizedEvent.InputTuple,
      GovernanceAuthorizedEvent.OutputTuple,
      GovernanceAuthorizedEvent.OutputObject
    >;
    GovernanceAuthorized: TypedContractEvent<
      GovernanceAuthorizedEvent.InputTuple,
      GovernanceAuthorizedEvent.OutputTuple,
      GovernanceAuthorizedEvent.OutputObject
    >;

    "KYCVerified(address,bytes32,uint256)": TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;
    KYCVerified: TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;

    "LenderAuthorized(address,bool)": TypedContractEvent<
      LenderAuthorizedEvent.InputTuple,
      LenderAuthorizedEvent.OutputTuple,
      LenderAuthorizedEvent.OutputObject
    >;
    LenderAuthorized: TypedContractEvent<
      LenderAuthorizedEvent.InputTuple,
      LenderAuthorizedEvent.OutputTuple,
      LenderAuthorizedEvent.OutputObject
    >;

    "LiquidationRegistered(address,uint256,uint256,uint256,address)": TypedContractEvent<
      LiquidationRegisteredEvent.InputTuple,
      LiquidationRegisteredEvent.OutputTuple,
      LiquidationRegisteredEvent.OutputObject
    >;
    LiquidationRegistered: TypedContractEvent<
      LiquidationRegisteredEvent.InputTuple,
      LiquidationRegisteredEvent.OutputTuple,
      LiquidationRegisteredEvent.OutputObject
    >;

    "LoanRegistered(address,uint256,uint256,uint256,address)": TypedContractEvent<
      LoanRegisteredEvent.InputTuple,
      LoanRegisteredEvent.OutputTuple,
      LoanRegisteredEvent.OutputObject
    >;
    LoanRegistered: TypedContractEvent<
      LoanRegisteredEvent.InputTuple,
      LoanRegisteredEvent.OutputTuple,
      LoanRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalRecorded(address,uint256,uint256)": TypedContractEvent<
      ProposalRecordedEvent.InputTuple,
      ProposalRecordedEvent.OutputTuple,
      ProposalRecordedEvent.OutputObject
    >;
    ProposalRecorded: TypedContractEvent<
      ProposalRecordedEvent.InputTuple,
      ProposalRecordedEvent.OutputTuple,
      ProposalRecordedEvent.OutputObject
    >;

    "RepaymentRegistered(address,uint256,uint256,uint256,address)": TypedContractEvent<
      RepaymentRegisteredEvent.InputTuple,
      RepaymentRegisteredEvent.OutputTuple,
      RepaymentRegisteredEvent.OutputObject
    >;
    RepaymentRegistered: TypedContractEvent<
      RepaymentRegisteredEvent.InputTuple,
      RepaymentRegisteredEvent.OutputTuple,
      RepaymentRegisteredEvent.OutputObject
    >;

    "StakeDeposited(address,uint256,uint256)": TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;
    StakeDeposited: TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;

    "VoteRecorded(address,uint256,uint256)": TypedContractEvent<
      VoteRecordedEvent.InputTuple,
      VoteRecordedEvent.OutputTuple,
      VoteRecordedEvent.OutputObject
    >;
    VoteRecorded: TypedContractEvent<
      VoteRecordedEvent.InputTuple,
      VoteRecordedEvent.OutputTuple,
      VoteRecordedEvent.OutputObject
    >;
  };
}
