/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ScoreOracleMultiWallet {
  export type ScoreBreakdownStruct = {
    overall: BigNumberish;
    s1_repayment: BigNumberish;
    s2_collateral: BigNumberish;
    s3_sybil: BigNumberish;
    s4_crossChain: BigNumberish;
    s5_governance: BigNumberish;
    s3_raw: BigNumberish;
    isAggregate: boolean;
    walletCount: BigNumberish;
  };

  export type ScoreBreakdownStructOutput = [
    overall: bigint,
    s1_repayment: bigint,
    s2_collateral: bigint,
    s3_sybil: bigint,
    s4_crossChain: bigint,
    s5_governance: bigint,
    s3_raw: bigint,
    isAggregate: boolean,
    walletCount: bigint
  ] & {
    overall: bigint;
    s1_repayment: bigint;
    s2_collateral: bigint;
    s3_sybil: bigint;
    s4_crossChain: bigint;
    s5_governance: bigint;
    s3_raw: bigint;
    isAggregate: boolean;
    walletCount: bigint;
  };
}

export interface ScoreOracleMultiWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIER_GOLD"
      | "TIER_PLATINUM"
      | "TIER_SILVER"
      | "computeScore"
      | "getAPR"
      | "getScoreTier"
      | "isSupportedChain"
      | "owner"
      | "registry"
      | "renounceOwnership"
      | "setUserRegistry"
      | "supportedChainSelectors"
      | "transferOwnership"
      | "userRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "UserRegistryUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "TIER_GOLD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "TIER_PLATINUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIER_SILVER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAPR",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScoreTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setUserRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChainSelectors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "TIER_GOLD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TIER_PLATINUM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIER_SILVER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAPR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getScoreTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChainSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRegistry",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegistryUpdatedEvent {
  export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
  export type OutputTuple = [oldRegistry: string, newRegistry: string];
  export interface OutputObject {
    oldRegistry: string;
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ScoreOracleMultiWallet extends BaseContract {
  connect(runner?: ContractRunner | null): ScoreOracleMultiWallet;
  waitForDeployment(): Promise<this>;

  interface: ScoreOracleMultiWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIER_GOLD: TypedContractMethod<[], [bigint], "view">;

  TIER_PLATINUM: TypedContractMethod<[], [bigint], "view">;

  TIER_SILVER: TypedContractMethod<[], [bigint], "view">;

  computeScore: TypedContractMethod<
    [wallet: AddressLike],
    [ScoreOracleMultiWallet.ScoreBreakdownStructOutput],
    "view"
  >;

  getAPR: TypedContractMethod<[overall: BigNumberish], [bigint], "view">;

  getScoreTier: TypedContractMethod<[overall: BigNumberish], [bigint], "view">;

  isSupportedChain: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setUserRegistry: TypedContractMethod<
    [_userRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  supportedChainSelectors: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIER_GOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_PLATINUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIER_SILVER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeScore"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [ScoreOracleMultiWallet.ScoreBreakdownStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAPR"
  ): TypedContractMethod<[overall: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScoreTier"
  ): TypedContractMethod<[overall: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isSupportedChain"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserRegistry"
  ): TypedContractMethod<[_userRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedChainSelectors"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistryUpdated"
  ): TypedContractEvent<
    UserRegistryUpdatedEvent.InputTuple,
    UserRegistryUpdatedEvent.OutputTuple,
    UserRegistryUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UserRegistryUpdated(address,address)": TypedContractEvent<
      UserRegistryUpdatedEvent.InputTuple,
      UserRegistryUpdatedEvent.OutputTuple,
      UserRegistryUpdatedEvent.OutputObject
    >;
    UserRegistryUpdated: TypedContractEvent<
      UserRegistryUpdatedEvent.InputTuple,
      UserRegistryUpdatedEvent.OutputTuple,
      UserRegistryUpdatedEvent.OutputObject
    >;
  };
}
