/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationScorer,
  IReputationScorerInterface,
} from "../../../contracts/HealthFactorMonitor.sol/IReputationScorer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getDynamicLTV",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReputationScorer__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationScorerInterface {
    return new Interface(_abi) as IReputationScorerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationScorer {
    return new Contract(address, _abi, runner) as unknown as IReputationScorer;
  }
}
