/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFlashLoanReceiver,
  IFlashLoanReceiverInterface,
} from "../../../../contracts/interfaces/IFlashLoanReceiver.sol/IFlashLoanReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "premium",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "executeOperation",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFlashLoanReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IFlashLoanReceiverInterface {
    return new Interface(_abi) as IFlashLoanReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFlashLoanReceiver {
    return new Contract(address, _abi, runner) as unknown as IFlashLoanReceiver;
  }
}
